# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQeU0azb9Nwhu8n9K3mKZ09pbuZhmtL7
"""

# Simple Calculator Program

def add(x, y):      #calculate addition
    return x + y

def subtract(x, y): #calculate subtraction
    return x - y

def multiply(x, y): #calculate multiplication
    return x * y

def divide(x, y):   #calculate division
    if y == 0:
        return "Error: Division by zero is undefined." #checking if the second number is zero then show error
    return x / y

# Main program loop
while True:
    print("\nSimple Calculator") #Displaying Menu Options
    print("1. Add")
    print("2. Subtract")
    print("3. Multiply")
    print("4. Divide")
    print("5. Exit")

    choice = input("Enter your choice (1-5): ") #inputting choice by user

    if choice == '5':
        print("Exiting calculator. Goodbye!")
        break

    if choice in ('1', '2', '3', '4'):   #loop to check which operation have to be performed
        try:
            num1 = float(input("Enter first number: "))   #inputting 1st number
            num2 = float(input("Enter second number: "))  #inputting 2nd number
        except ValueError:           #checking if the inputs are numbers or not
            print("Invalid input. Please enter numeric values.")
            continue

        if choice == '1':
            print("Result:", add(num1, num2))       #calling add function
        elif choice == '2':
            print("Result:", subtract(num1, num2))  #calling subtract function
        elif choice == '3':
            print("Result:", multiply(num1, num2))  #calling multiply function
        elif choice == '4':
            print("Result:", divide(num1, num2))    #calling divide function
    else:
        print("Invalid choice. Please select a valid option.")  #if choice is not in the list then displaying message