# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1af9AUdq2Z0AlYMTLaNsy1TihtnI7HB2m
"""

print("Hello World !! ")  #printing Hello World
print("Name: Vartika Kashyap") #printing name
print("Email Id: 24150cn074@glbitm.ac.in")  #printing mail id
print(3+6) #adding two numbers
z=0 #initializing values in z
print("z=",z) #printing value of z